resolver: lts-5.12

packages:
- .
  # authenticate-oauth patched package, remains here until my patch is merged
- location:
    git: https://github.com/achirkin/authenticate.git
    commit: 3e150189eaeb56d26f453f1258e8fe8f7f9a795a
  extra-dep: true
  subdirs:
  - authenticate-oauth
  # ltiv1p1 package is an LTI 1.1 provider partial implementation
- location:
    git: https://github.com/achirkin/qua-kit.git
    commit: ea8b30808ead17c0fd047dd18a6e7af05bd1f0ed
  extra-dep: true
  subdirs:
  - libs/hs/ltiv1p1
