resolver: lts-6.2
extra-deps:
  - directory-1.2.6.3
    # authenticate-oauth patched package, remains here until comes to stackage
  - authenticate-oauth-1.6
    # ltiv1p1 package is an LTI 1.1 provider partial implementation
  - ltiv1p1-1.0.0.1

packages:
  - .
